# creating random values

# rand()

In [2]:
import numpy as np
var = np.random.rand(4)
print(var)

[0.11782179 0.58902695 0.82243205 0.97123836]


In [4]:
# 2-D
var1 =np.random.rand(2,5)
print(var1)

[[0.65339825 0.60625191 0.67597787 0.41720674 0.69081069]
 [0.01612898 0.90119834 0.4419436  0.78943472 0.58424297]]


In [13]:
# 3-D
var1 =np.random.rand(2,3,3)
print(var1)

[[[0.80202645 0.75984601 0.38015621]
  [0.15375439 0.99495082 0.84901138]
  [0.44408233 0.3901886  0.20517607]]

 [[0.51965932 0.19404181 0.51898462]
  [0.93769961 0.82915434 0.57136238]
  [0.89361228 0.7760218  0.20759708]]]


# randn()

In [6]:
sar1 = np.random.randn(7)
print(sar1)

[-0.67923343  0.22054109 -0.96685525  1.6165699  -0.14851022  0.15122668
 -1.33993841]


In [9]:
# 2-D
sar2 = np.random.randn(3,3)
print(sar2)

[[ 1.56794946  1.00675172  0.5389033 ]
 [-0.09134019  0.4780924  -0.25871607]
 [-0.58000368 -0.13738536 -1.11076219]]


In [10]:
# 3-D
sar2 = np.random.randn(3,3,3)
print(sar2)

[[[ 0.56521026 -0.67281461  0.45145927]
  [ 0.730344    1.82858247  1.77922573]
  [ 0.73341969  0.35422369 -1.75718194]]

 [[ 0.98755014 -0.02025558  0.69099851]
  [ 0.03482035  1.28350777 -1.51920228]
  [-0.73589373 -0.66432422  0.08647435]]

 [[-0.68660767 -1.44309452 -1.56430198]
  [ 0.51147945  0.98046057  1.1411509 ]
  [-0.36726517  0.0787714   1.05352299]]]


# ranf()

In [18]:
rf = np.random.ranf(3)
print(rf)

[0.98906939 0.37507235 0.77590117]


# randint()

In [28]:
rnd = np.random.randint(2,10,3)# min, max, total_number
print(rnd)

[5 4 4]


# Data types in numpy array

- bool_
- int_
- intc
- intp
- int8
- int16
- int32
- int64
- uint8
- uint16
- uint32
- uint64
- float_
- float16
- float32
- float64
- complax
- complax64
- complax 128

In [34]:
import numpy as np
var = np.array([1,2,3,4])
print("data type: ",var.dtype)

data type:  int32


In [35]:
import numpy as np
var = np.array([1.2,2.3,3.4,4.5])
print("data type: ",var.dtype)

data type:  float64


In [36]:
import numpy as np
var = np.array(["name", "sajawal", "Bilal"])
print("data type: ",var.dtype)

data type:  <U7


In [38]:
import numpy as np
var = np.array(["name", "sajawal", "Bilal",1,2,3,4])
print("data type: ",var.dtype)

data type:  <U7


# Data types

- Data types as functions
- i-	integer
- b-	Boolean
- u-	Unsigned integer
- f-   	float
- c-	complex float
- m-	timedelta
- M-	datetime
- O-	Object
- S-	String
- U-	Unicode string
- V-	the fixed chunk of memory for other types (void)


In [41]:
x = np.array([1,2,3,4,5], dtype = np.int8)
print(x, "DaTa type: ",x.dtype)

[1 2 3 4 5] DaTa type:  int8


In [42]:
x1 = np.array([1,2,3,4,5], dtype = "f")
print(x, "DaTa type: ",x1.dtype)

[1 2 3 4 5] DaTa type:  float32


In [46]:
x2 = np.array([1,2,3,4,5])

new = np.float32(x2)

new_one = np.int_(new)
print("DaTa type: ",x2.dtype)
print("Data type: ", new.dtype)
print("Data type: ", new_one.dtype)
print(x2)
print(new)
print(new_one)

DaTa type:  int32
Data type:  float32
Data type:  int32
[1 2 3 4 5]
[1. 2. 3. 4. 5.]
[1 2 3 4 5]


In [47]:
x3 = np.array([1,2,3,4,5])
new1 = x3.astype(float)
print(x3)
print(new1)

[1 2 3 4 5]
[1. 2. 3. 4. 5.]


# shape and reshaping in Numpy Arrays

# shape

In [51]:
import numpy as np
var = np.array([[1,2,3,4],[3,4,4,4]])
print(var)
print(var.shape)

[[1 2 3 4]
 [3 4 4 4]]
(2, 4)


In [40]:
import numpy as np
var = np.array([1,2,3,4], ndmin = 4)
print(var)
print()
print(var.ndim)
print(var.shape)

[[[[1 2 3 4]]]]

4
(1, 1, 1, 4)


# reshape

In [8]:
import numpy as np
var2 = np.array([2,3,4,5,6,3])
print(var2,var2.ndim)
print()
x = var2.reshape(3,2)
print(x,x.ndim)

[2 3 4 5 6 3] 1

[[2 3]
 [4 5]
 [6 3]] 2


In [22]:
# 3-Dimension array
import numpy as np
var3 = np.array([2,3,4,5,6,3,4,5,6,8,9,0])
print(var3,var3.ndim)
print()
x = var3.reshape(2,3,2)
print(x,x.ndim)
print()
one = x.reshape(-1)
print(one,one.ndim)

[2 3 4 5 6 3 4 5 6 8 9 0] 1

[[[2 3]
  [4 5]
  [6 3]]

 [[4 5]
  [6 8]
  [9 0]]] 3

[2 3 4 5 6 3 4 5 6 8 9 0] 1


# Arithmatic Operations in Numpy Arrays

In [25]:
import numpy as np
# addition in 1-D
var1 = np.array([1,2,3,4])
print(var1)
print()
var_add = var1+3
print(var_add)

[1 2 3 4]

[4 5 6 7]


In [26]:
import numpy as np
# addition in 1-D
var1 = np.array([1,2,3,4])
var2 = np.array([5,6,7,8])
var_add = var1+var2
print(var_add)

[ 6  8 10 12]


In [27]:
import numpy as np
# subtraction in 1-D
var1 = np.array([1,2,3,4])
var2 = np.array([5,6,7,8])
var_minus = var1-var2
print(var_minus)

[-4 -4 -4 -4]


In [28]:
import numpy as np
# multiplication in 1-D
var1 = np.array([1,2,3,4])
var2 = np.array([5,6,7,8])
var_mul = var1*var2
print(var_mul)

[ 5 12 21 32]


In [32]:
import numpy as np
# modulus in 1-D
var1 = np.array([1,2,3,4])
var2 = np.array([5,6,7,8])
var_mod = var2%var1
print(var_mod)

[0 0 1 0]


In [34]:
# numpy function
var1 = np.array([1,2,3,4])
var2 = np.array([5,6,7,8])
var_add = np.add(var1,3)
print(var_add)

[4 5 6 7]


In [36]:
# numpy function
var1 = np.array([1,2,3,4])
var2 = np.array([5,6,7,8])
var_sub = np.subtract(var1,3)
print(var_sub)

[-2 -1  0  1]


# 2D array

In [16]:
import numpy as np
var1 = np.arange(6).reshape(2,3)
var2 = np.arange(6).reshape(2,3)
print(var1)
print(var2)
print()
var_multiply = np.multiply(var1,var2)
print(var_multiply)



[[0 1 2]
 [3 4 5]]
[[0 1 2]
 [3 4 5]]

[[ 0  1  4]
 [ 9 16 25]]


In [38]:
var3 = np.array([1,2,4,6,4,4,3,2])
print(np.max(var3))# maximum
print()
print(np.min(var3))# minimum
print()
print(np.argmin(var3))# location of minimum value
print()
print(np.argmax(var3)) # location of maximum value
print(np.cumsum(var3)) 

6

1

0

3
[ 1  3  7 13 17 21 24 26]


In [37]:
var12 = np.array([[2,3,4,5,6],[4,5,6,1,7]])
print(var12)
print(np.argmax(var12))
print(np.min(var12, axis=0))
print(np.sqrt(var12))

[[2 3 4 5 6]
 [4 5 6 1 7]]
9
[2 3 4 1 6]
[[1.41421356 1.73205081 2.         2.23606798 2.44948974]
 [2.         2.23606798 2.44948974 1.         2.64575131]]


# Broadcasting  Numpy Arrays

- The term broadcasting describes how numpy treats arrays with different shapes during arithmetic operations. Subject to certain constraints, the smaller array is “broadcast” across the larger array so that they have compatible shapes

In [11]:
import numpy as np
var1 = np.array([1,2,3])
print(var1)
print(var1.shape)
print()
var2 = np.array([[1],[2],[3]])
print(var2,var2.shape)
print()
print(var1+var2)


[1 2 3]
(3,)

[[1]
 [2]
 [3]] (3, 1)

[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [12]:
var1 = np.array([1,2,3])
print(var1)
print(var1.shape)
print()
var2 = np.array([[1],[2],[3]])
print(var2,var2.shape)
print()
print(var1*var2)


[1 2 3]
(3,)

[[1]
 [2]
 [3]] (3, 1)

[[1 2 3]
 [2 4 6]
 [3 6 9]]


In [33]:
# 2*1 and 2*3
x = np.array([[1],[2]])
print(x.shape)
print(x)
y = np.array([[1,2,3],[4,5,6]])
print(y.shape)
print(y)
print()
var = x+y
print(var)

(2, 1)
[[1]
 [2]]
(2, 3)
[[1 2 3]
 [4 5 6]]

[[2 3 4]
 [6 7 8]]


# indexing  

In [35]:
# 1-D
var = np.array([1,2,3,4,5])
print(var[-2])

4


In [42]:
# 2-D
var1= np.array([[1,2,3],[4,5,6]])
print(var1[1,2])
print(var1[0,1])

6
2


In [78]:
# 3-D
var2 = np.array([[[2,0,9],[3,4,5],[6,7,8]]])
print(var2,var2.ndim)
print(var2[0,1,1])
print(var2[0,2,0])

[[[2 0 9]
  [3 4 5]
  [6 7 8]]] 3
4
6


# slicing

In [65]:
x = np.array([1,2,3,4,5,6,7,8,9])
print(x[0:4:1]) # slicing(0 start from, 4 end in, 1 steps)

[1 3]


In [82]:
x =np.array([[1,2,3,4,5],[6,7,3,4,5]])
print(x[0,1:])

[2 3 4 5]


# Iterating Numpy Arrays

In [89]:
# 2-D array
x =np.array([[1,2,3,4,5],[6,7,3,4,5]])
for i in x:
    print(i)
print()
for k in x:
    for l in k:
        print(l)

[1 2 3 4 5]
[6 7 3 4 5]

1
2
3
4
5
6
7
3
4
5


In [90]:
# 3-D array
y = np.array([[[1,2,3,4],[1,2,3,4],[1,2,3,4]]])
for i in y:
    for j in i:
        for k in j:
            print(k)

1
2
3
4
1
2
3
4
1
2
3
4


In [92]:
y = np.array([[[1,2,3,4],[1,2,3,4],[1,2,3,4]]])
for i in np.nditer(y):
    print(i)

1
2
3
4
1
2
3
4
1
2
3
4


In [95]:
y = np.array([[[1,2,3,4],[1,2,3,4],[1,2,3,4]]])
for i in np.ndenumerate(y):
    print(i)

(array([[[1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4]]]), [[[1, 2, 3, 4], [1, 2, 3, 4], [1, 2, 3, 4]]])
((0, 0, 0, 0), 1)
((0, 0, 0, 1), 2)
((0, 0, 0, 2), 3)
((0, 0, 0, 3), 4)
((0, 0, 1, 0), 1)
((0, 0, 1, 1), 2)
((0, 0, 1, 2), 3)
((0, 0, 1, 3), 4)
((0, 0, 2, 0), 1)
((0, 0, 2, 1), 2)
((0, 0, 2, 2), 3)
((0, 0, 2, 3), 4)
((1, 0, 0, 0), 1)
((1, 0, 0, 1), 2)
((1, 0, 0, 2), 3)
((1, 0, 0, 3), 4)
((1, 0, 1, 0), 1)
((1, 0, 1, 1), 2)
((1, 0, 1, 2), 3)
((1, 0, 1, 3), 4)
((1, 0, 2, 0), 1)
((1, 0, 2, 1), 2)
((1, 0, 2, 2), 3)
((1, 0, 2, 3), 4)


# copy vs view

In [98]:
z = np.array([1,2,3,4])
co = z.copy()
print("z", z)
print("co", co)

z [1 2 3 4]
co [1 2 3 4]


In [99]:
d = np.array([9,6,5,4,6])
vi = d.view()
print("d", d)
print("vi", vi)

d [9 6 5 4 6]
vi [9 6 5 4 6]


# join array

In [101]:
# 1-D
var = np.array([1,2,3,4])
var1 = np.array([5,6,7,8])
sa = np.concatenate((var,var1))
print(sa)

[1 2 3 4 5 6 7 8]


In [108]:
# 2-D
var2 = np.array([[1,2,3,4],[5,6,7,8]])
var3 =np.array([[1,2,3,4],[2,3,4,5]])
sa2 = np.concatenate((var2,var3),axis = 1)
print(sa2)

[[1 2 3 4 1 2 3 4]
 [5 6 7 8 2 3 4 5]]


In [129]:
vr = np.array([1,2,3,4])
vr1 = np.array([5,6,7,8])
sa = np.hstack((vr,vr1))# row 
sa2 = np.vstack((vr,vr1))# column
sa3 = np.dstack((vr,vr1))# height
print(sa)
print()
print(sa2)
print()
print(sa3)

[1 2 3 4 5 6 7 8]

[[1 2 3 4]
 [5 6 7 8]]

[[[1 5]
  [2 6]
  [3 7]
  [4 8]]]


# split 

In [132]:
vr = np.array([1,2,3,4])
ar = np.array_split(vr,2)# variable name, arrays we want split into it
print(ar)

[array([1, 2]), array([3, 4])]


In [142]:
vr1 = np.array([[1,2,3,4],[3,4,5,6]])
ar1 = np.array_split(vr1,4, axis=0)
print(ar1)


[array([[1, 2, 3, 4]]), array([[3, 4, 5, 6]]), array([], shape=(0, 4), dtype=int32), array([], shape=(0, 4), dtype=int32)]


# search
- search an array for a certain value, and return the indexes that get a match.

In [147]:
vs = np.array([2,3,4,5,66,4,3,3,22,1])
av = np.where(vs%2==0) # at indexes of 1, 6 and 7
av

(array([0, 2, 4, 5, 8], dtype=int64),)

# search sorted array
- Search sorted array:  which performs a binary search in the array, and returns the index where the specified value would be inserted to maintain the search order.

In [171]:
gs = np.array([2,3,4,5,8,9,10])
av = np.searchsorted(gs,[2]) # at indexes of 1, 6 and 7
av

array([0], dtype=int64)

# sort
- ordered sequence is any sequence that has an order corresponding to elements, like numeric or alphabetical, ascending or decending

In [173]:
ve = np.array([3,4,5,3,1,2,3,4,5,7,8,99,9])
se = np.sort(ve)
se

array([ 1,  2,  3,  3,  3,  4,  4,  5,  5,  7,  8,  9, 99])

In [174]:
vs = np.array(["a","z","d","g","f"])
ss = np.sort(vs)
ss

array(['a', 'd', 'f', 'g', 'z'], dtype='<U1')

In [177]:
# 2-D array
ve = np.array([[3,4,5,3,1,2,3,4,5,7,8,99,9],[3,42,22,1,1,21,21,12,34,12,3,4,5]])
se = np.sort(ve)
se

array([[ 1,  2,  3,  3,  3,  4,  4,  5,  5,  7,  8,  9, 99],
       [ 1,  1,  3,  3,  4,  5, 12, 12, 21, 21, 22, 34, 42]])

# filter array
- Getting some elements out of an existing array and creating a new array out of them

In [179]:
fila = np.array(["a","b","f","g","z"])
y = [True,False, True, True,False]
new_a = fila[y]
print(new_a)

['a' 'f' 'g']


# Arithmetic Functions :
- •	Shuffle
- •	Unique
- •	Resize
- •	Flatten
- •	Ravel


In [184]:
shuf = np.array([1,2,3,4,5,6])
np.random.shuffle(shuf)
print(shuf)

[1 6 3 4 5 2]


In [4]:
# unique
import numpy as np
x = np.array([1,2,2,2,3,4,33,2,2,1,2,2,15,6,7,8,9])
y = np.unique(x, return_index=True, return_counts=True)
print(y)

(array([ 1,  2,  3,  4,  6,  7,  8,  9, 15, 33]), array([ 0,  1,  4,  5, 13, 14, 15, 16, 12,  6], dtype=int64), array([2, 7, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int64))


In [6]:
# resize
var = np.array([1,2,3,4,5,6,7])
y = np.resize(var,(3,2))
print(y)

[[1 2]
 [3 4]
 [5 6]]


In [16]:
# flatten
var = np.array([1,2,3,4,5,6,7])
y = np.resize(var,(3,2))
print(y.flatten(order = "C"))
print("raval : ",np.ravel(y, order = "F"))

[1 2 3 4 5 6]
raval :  [1 3 5 2 4 6]


# Insert and Delete Function

In [21]:
# insert
import numpy as np
x = np.array([1,2,3,4])
v= np.insert(x, (2,4), 14)
print(v)

[ 1  2 14  3  4 14]


In [30]:
# 2-D
var1 = np.array([[1,2,3,4],[2,3,4,5]])
v1 = np.insert(var1, (2,4), [6,7], axis =1)
print(v1)

[[1 2 6 3 4 7]
 [2 3 6 4 5 7]]


In [31]:
# Delete
x = np.array([1,2,3,4])
v2 = np.delete(x,3)
print(v2)

[1 2 3]
