In [1]:
import numpy as np
a = np. arange(6)
a2 = a[np.newaxis, :]
a2.shape

(1, 6)

In [2]:
import numpy as np
a = np.array([2,3,4,4,5,5])
a

array([2, 3, 4, 4, 5, 5])

In [3]:
type(a)

numpy.ndarray

In [4]:
# list of lists
import numpy as np
b = np.array([[22,24,23,29],
             [33,35,36,37],
             [44,47,43,45]])
b

array([[22, 24, 23, 29],
       [33, 35, 36, 37],
       [44, 47, 43, 45]])

In [5]:
type(b)

numpy.ndarray

In [6]:
# list of lists
import numpy as np
b = np.array([[22,24,23,29],
             [33,35,36,37],
             [44,47,43,45]])

b[1,3]

37

In [7]:
import numpy as np
# 2-D or 2-axis   and it is 2*3
a = np.array([[5,5,5,5],
              [6,6,6,6]])
a

array([[5, 5, 5, 5],
       [6, 6, 6, 6]])

In [8]:
import numpy as np
a = np.zeros(2)
a

array([0., 0.])

In [9]:
import numpy as np
a = np.ones(3)
a

array([1., 1., 1.])

In [10]:
import numpy as np
a = np.empty(3)
a

array([1., 1., 1.])

In [11]:
import numpy as np
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [12]:
a = np.arange(1,6)
a

array([1, 2, 3, 4, 5])

In [13]:
a = np.arange(2,20,3)
a

array([ 2,  5,  8, 11, 14, 17])

In [14]:
# linearly spaced arrays
h = np.linspace(0,10,num=5)
h

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [15]:
# 2-d 
g = np.zeros((3,4))
g
f = np.ones((4,3))
f

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [16]:
import numpy as np
# making and reshaping 3-D dimension
k = np.arange(24).reshape(2, 3, 4)
k

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [17]:
i = np.ones(4, dtype=np.int8)
i

array([1, 1, 1, 1], dtype=int8)

In [18]:
j = np.empty(6, dtype=np.float64)
j

array([0., 0., 0., 0., 0., 0.])

### Part 2

In [19]:
import numpy as np

# creating an array
# 1-D array
food = np.array(["Pakora", "smosa", "Raita"])
food

array(['Pakora', 'smosa', 'Raita'], dtype='<U6')

In [20]:
prices = np.array([5,5,5])
prices

array([5, 5, 5])

In [21]:
len(prices)

3

In [22]:
len(food)

3

In [23]:
prices[2]

5

In [24]:
prices.mean()

5.0

In [25]:
# zeros
a = np.zeros(6)
a

array([0., 0., 0., 0., 0., 0.])

In [26]:
# ones
b = np.ones(6)
b

array([1., 1., 1., 1., 1., 1.])

In [27]:
# empty
c = np.empty(6)
c

array([1., 1., 1., 1., 1., 1.])

In [28]:
# range
d = np.arange(10)
d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
# specific interval
e = np.arange(2,10,2)
e

array([2, 4, 6, 8])

In [30]:
# table of five
f = np.arange(0,55,5)
f

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [31]:
# line space
g = np.linspace(1, 100, num=20)
g

array([  1.        ,   6.21052632,  11.42105263,  16.63157895,
        21.84210526,  27.05263158,  32.26315789,  37.47368421,
        42.68421053,  47.89473684,  53.10526316,  58.31578947,
        63.52631579,  68.73684211,  73.94736842,  79.15789474,
        84.36842105,  89.57894737,  94.78947368, 100.        ])

In [32]:
# specify your data type
h= np.ones(50,dtype=np.int64)
h

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1], dtype=int64)

In [33]:
# specify your data type
h= np.ones(50,dtype=np.float64)
h

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [34]:
# array functions
j = np.array([10,30,40,5,5.3,6.5,3])
j

array([10. , 30. , 40. ,  5. ,  5.3,  6.5,  3. ])

In [35]:
j.sort()
j

array([ 3. ,  5. ,  5.3,  6.5, 10. , 30. , 40. ])

In [36]:
j.any()
j

array([ 3. ,  5. ,  5.3,  6.5, 10. , 30. , 40. ])

In [37]:
j.argmax()
j

array([ 3. ,  5. ,  5.3,  6.5, 10. , 30. , 40. ])

In [38]:
k = np.array([22,44,32,42,5.3,5.3,2.3])
l = np.concatenate((j,k))
l

array([ 3. ,  5. ,  5.3,  6.5, 10. , 30. , 40. , 22. , 44. , 32. , 42. ,
        5.3,  5.3,  2.3])

In [39]:
l.sort()
l

array([ 2.3,  3. ,  5. ,  5.3,  5.3,  5.3,  6.5, 10. , 22. , 30. , 32. ,
       40. , 42. , 44. ])

In [40]:
# 2-D array
a = np.array([[22,33,44,55],[45,64,54,63]])
a

array([[22, 33, 44, 55],
       [45, 64, 54, 63]])

In [41]:
b = np.array([[6,4,6,4],[7,8,6,5]])
b

array([[6, 4, 6, 4],
       [7, 8, 6, 5]])

In [42]:
c = np.concatenate((a,b), axis = 1)
c

array([[22, 33, 44, 55,  6,  4,  6,  4],
       [45, 64, 54, 63,  7,  8,  6,  5]])

In [43]:
import numpy as np
a = np.arange(1, 10).reshape(3, 3)
b = np.arange(10, 19).reshape(3, 3)
c = np.concatenate((a,b), axis=1)
c


array([[ 1,  2,  3, 10, 11, 12],
       [ 4,  5,  6, 13, 14, 15],
       [ 7,  8,  9, 16, 17, 18]])

In [44]:
# to find the number of dimension
c.ndim

2

In [45]:
e =np.array ([[2,3,4],
      [4,6,7],
     [9,8,7]])
e

array([[2, 3, 4],
       [4, 6, 7],
       [9, 8, 7]])

In [46]:
e.ndim

2

In [47]:
# no of elements
e.size

9

In [48]:
# shape of array
e.shape

(3, 3)

In [49]:
a = np.arange(6).reshape(3,2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [50]:
# convert 1-D array into 2-D array
a = np.array([4,5,6,7,8,9])
a.shape

(6,)

In [51]:
b = a[np.newaxis, :]
b

array([[4, 5, 6, 7, 8, 9]])

In [52]:
b.shape

(1, 6)

In [53]:
# columnwise conversion
c = a[:, np.newaxis,]
c

array([[4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [54]:
c.sum()

39

In [55]:
c.mean()

6.5

In [56]:
c*5

array([[20],
       [25],
       [30],
       [35],
       [40],
       [45]])

In [57]:
c+6

array([[10],
       [11],
       [12],
       [13],
       [14],
       [15]])

### Complete Numpy tutorial (4hours)

In [58]:
import numpy as np
x = [1,2,3,4]
y = np.array(x)
x
print(y)
print(type(y))

[1 2 3 4]
<class 'numpy.ndarray'>


In [60]:
l.ndim

AttributeError: 'list' object has no attribute 'ndim'

In [ ]:
import numpy as np
ac = np.array([[2,3,4,5,6,7,8],
               [2,3,4,5,6,4,4]])
print(ac)

In [76]:
ar3 = np.array([[[1,2,3,4],[5,6,7,8],[0,9,8,7]]])
print(ar3)
print(ar3.ndim)

[[[1 2 3 4]
  [5 6 7 8]
  [0 9 8 7]]]
3


In [77]:
# n / multi dimensional array
arn = np.array([1,2,3,4], ndmin = 10)
print(arn)
print(arn.ndim)

[[[[[[[[[[1 2 3 4]]]]]]]]]]
10


# Zero's

In [78]:
zero1 = np.zeros(4)
zero2 = np.zeros((3,4))
print(zero1)
print(zero2)

[0. 0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


# One's

In [79]:
one1 = np.ones(4)
one2 = np.ones((3,4))
print(one1)
print(one2)

[1. 1. 1. 1.]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


# Empty's

In [63]:
import numpy as np
ar = np.empty(5)
ar

array([9.76118064e-313, 2.12199579e-312, 2.31297541e-312, 0.00000000e+000,
       1.37959808e-306])

# Range's

In [65]:
ran = np.arange(1,4)
print(ran)

[1 2 3]


In [66]:
ran1 = np.arange(1,10, 2)
print(ran1)

[1 3 5 7 9]


In [75]:
ran2 = np.arange(24).reshape(2,3,4)
(ran2)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

# Diagonal

In [84]:
ar_dia = np.eye(3)
print(ar_dia)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# Linespace

In [88]:
# libespace
al = np.linspace(0,10, num=5)
al

array([ 0. ,  2.5,  5. ,  7.5, 10. ])